env:
  global:
    - CC_TEST_REPORTER_ID=ABC123

language: ruby
before_install: gem install bundler

rvm:
  - 2.6.1
  - 2.3.0
  - jruby-head

gemfile:
  - Gemfile

notifications:
  email: true

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - bundle exec rspec

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
